name: AoC18-Haskell
version: 0.1.0.0
github: "Riddarvid/AoC18-Haskell"
license: BSD3
author: "Riddarvid"
maintainer: "44440210+Riddarvid@users.noreply.github.com"
copyright: "2023 Riddarvid"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/Riddarvid/AoC18-Haskell#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.6
  - unordered-containers >= 0.2.19.0
  - parsec >= 3.1.15.0
  - regex-pcre >= 0.95.0.0
  - mtl >= 2.2.2

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs:
    - src

executables:
  AoC18-Haskell-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AoC18-Haskell

tests:
  AoC18-Haskell-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - AoC18-Haskell
